export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";

export const FETCH_PROD = "FETCH_PROD";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_ITEM_CART = "INCREMENT_ITEM_CART";
export const DECREMENT_ITEM_CART = "DECREMENT_ITEM_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";